#!/usr/bin/env bash

# Run PHP-FPM as current user
if [ ! -z "$USER_UID" ]; then
    sed -i "s/user\ \=.*/user\ \= $USER_UID/g" /etc/php/7.4/fpm/pool.d/www.conf
    # Set UID of user "rpi"
    usermod -u $USER_UID rpi
    groupmod -g $USER_GID rpi
fi

# Run NFS server

# start rpcbind if it is not started yet
/usr/sbin/rpcinfo 127.0.0.1 > /dev/null; s=$?
if [[ ${s} -ne 0 ]]; then
   echo "Starting rpcbind"
   /sbin/rpcbind -w
fi

mount -t nfsd nfds /proc/fs/nfsd

# -V 3: enable NFSv3
/usr/sbin/rpc.mountd -N 2 -V 3
/usr/sbin/exportfs -r
# -G 10 to reduce grace time to 10 seconds (the lowest allowed)
/usr/sbin/rpc.nfsd -G 10 -N 2 -V 3
/sbin/rpc.statd --no-notify
echo "NFS started."

su - rpi -c "composer setup -d /api/"

# main entry point
/usr/bin/supervisord
